"use client";

import Image from "next/image";
import { FormEvent, useEffect, useState } from "react";
import { Building2, CalendarDays, Camera, Check, CircleGauge, Droplets, FileText, Gauge, Home, LayoutDashboard, Menu, Pencil, ReceiptText, Search, Settings, Upload, Users, X, Zap } from "lucide-react";

type Status="paid"|"pending"|"draft"; type View="dashboard"|"rooms"|"meters"|"bills"|"tenants"|"settings";
type Room={id:string;site:number;rent:number;tenant:string;phone:string;status:Status;oldWater:number;newWater:number;oldElectric:number;newElectric:number;meterPhotoKey?:string};
type Location={id:number;name:string;waterRate:number;electricRate:number};
type Totals={all:number;rent:number;water:number;power:number;paid:number};
const seedLocations:Location[]=[{id:1,name:"จุด 1",waterRate:18,electricRate:8},{id:2,name:"จุด 2",waterRate:20,electricRate:7.5},{id:3,name:"จุด 3",waterRate:15,electricRate:8.5}];
const names=["สมชาย ใจดี","พรทิพย์ แสงทอง","ณัฐพล มีสุข","สุรีย์พร ขยัน","วินัย คงมั่น","","กานดา พูนผล","วีระชัย มั่นคง","ดวงใจ งามดี","อาทิตย์ พร้อมใจ","นันทนา สุขสันต์","ธนา สมบูรณ์","มาลี รุ่งเรือง","นพดล ตั้งใจ"];
const ids=["A01","A02","A03","A04","A05","A06","B01","B02","B03","B04","B05","C01","C02","C03"];
const seedRooms:Room[]=ids.map((id,i)=>({id,site:i<6?1:i<11?2:3,rent:[3200,3500,3200,3800,3400,3600,3000,3200,3200,3400,3000,4200,4500,4000][i],tenant:names[i],phone:"",status:i%3===0?"paid":i%3===1?"pending":"draft",oldWater:70+i*5,newWater:77+i*5,oldElectric:420+i*27,newElectric:468+i*27}));
const money=(n:number)=>new Intl.NumberFormat("th-TH",{maximumFractionDigits:2}).format(n);
const viewNames:Record<View,string>={dashboard:"ภาพรวม",rooms:"ห้องพัก",meters:"จดมิเตอร์",bills:"บิล / ใบแจ้งหนี้",tenants:"ผู้เช่า",settings:"ตั้งค่าระบบ"};

export default function App(){
 const [view,setView]=useState<View>("dashboard"),[rooms,setRooms]=useState(seedRooms),[locations,setLocations]=useState(seedLocations),[edit,setEdit]=useState<Room|null>(null),[meterEdit,setMeterEdit]=useState<Room|null>(null),[mobile,setMobile]=useState(false),[query,setQuery]=useState(""),[site,setSite]=useState(0),[notice,setNotice]=useState("");
 useEffect(()=>{fetch("/api/data").then(r=>r.ok?r.json():Promise.reject()).then(d=>{setRooms(d.rooms);setLocations(d.locations)}).catch(()=>setNotice("กำลังแสดงข้อมูลตัวอย่าง—ฐานข้อมูลจะทำงานบนเว็บที่เผยแพร่"))},[]);
 const rate=(r:Room)=>locations.find(x=>x.id===r.site)??seedLocations[r.site-1];
 const bill=(r:Room)=>r.rent+(r.newWater-r.oldWater)*rate(r).waterRate+(r.newElectric-r.oldElectric)*rate(r).electricRate;
 const totals=rooms.reduce((a,r)=>{const b=bill(r);a.all+=b;a.rent+=r.rent;a.water+=(r.newWater-r.oldWater)*rate(r).waterRate;a.power+=(r.newElectric-r.oldElectric)*rate(r).electricRate;if(r.status==="paid")a.paid+=b;return a},{all:0,rent:0,water:0,power:0,paid:0});
 const filtered=rooms.filter(r=>(!site||r.site===site)&&(r.id.toLowerCase().includes(query.toLowerCase())||r.tenant.includes(query)));
 const navigate=(v:View)=>{setView(v);setMobile(false)};
 async function saveRoom(room:Room){setRooms(rs=>rs.map(r=>r.id===room.id?room:r));setEdit(null);setNotice("บันทึกข้อมูลห้อง "+room.id+" แล้ว");await fetch("/api/data",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({type:"room",id:room.id,data:room})}).catch(()=>{});}
 async function saveLocation(loc:Location){setLocations(ls=>ls.map(l=>l.id===loc.id?loc:l));setNotice("บันทึกเรตของ "+loc.name+" แล้ว");await fetch("/api/data",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({type:"location",id:loc.id,data:loc})}).catch(()=>{});}
 return <main className="shell">
  <aside className={`rail ${mobile?"show":""}`}><div className="logo"><Home/><span>บ้านเรา</span></div><button className="close-nav" onClick={()=>setMobile(false)}><X/></button><nav>
   <Nav icon={<LayoutDashboard/>} label="ภาพรวม" active={view==="dashboard"} onClick={()=>navigate("dashboard")}/><Nav icon={<Home/>} label="ห้องพัก" active={view==="rooms"} onClick={()=>navigate("rooms")}/><Nav icon={<Gauge/>} label="จดมิเตอร์" active={view==="meters"} onClick={()=>navigate("meters")}/><Nav icon={<FileText/>} label="บิล / ใบแจ้งหนี้" active={view==="bills"} onClick={()=>navigate("bills")}/><Nav icon={<ReceiptText/>} label="ใบเสร็จรับเงิน" active={view==="bills"} onClick={()=>navigate("bills")}/><Nav icon={<Users/>} label="ผู้เช่า" active={view==="tenants"} onClick={()=>navigate("tenants")}/><Nav icon={<Settings/>} label="ตั้งค่า" active={view==="settings"} onClick={()=>navigate("settings")}/>
  </nav></aside>
  <section className="workspace"><header><button className="hamb" onClick={()=>setMobile(true)}><Menu/></button><h1>{viewNames[view]}</h1><div className="header-filters"><button><CalendarDays/> กรกฎาคม 2569</button><select value={site} onChange={e=>setSite(Number(e.target.value))}><option value="0">ทุกจุด</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></div></header>
   {notice&&<div className="toast" onClick={()=>setNotice("")}><Check/> {notice}<X/></div>}
   <div className="page-body">
    {view==="dashboard"&&<Dashboard rooms={rooms} totals={totals} bill={bill} setView={navigate}/>} 
    {view==="rooms"&&<RoomsView rooms={filtered} query={query} setQuery={setQuery} locations={locations} onEdit={setEdit}/>} 
    {view==="meters"&&<MetersView rooms={filtered} onEdit={setMeterEdit}/>} 
    {view==="bills"&&<BillsView rooms={filtered} bill={bill} onEdit={setEdit}/>} 
    {view==="tenants"&&<TenantsView rooms={filtered} onEdit={setEdit}/>} 
    {view==="settings"&&<SettingsView locations={locations} onSave={saveLocation}/>} 
   </div>
  </section>
  {edit&&<><div className="shade" onClick={()=>setEdit(null)}/><RoomEditor room={edit} location={rate(edit)} onClose={()=>setEdit(null)} onSave={saveRoom}/></>}
  {meterEdit&&<><div className="shade" onClick={()=>setMeterEdit(null)}/><MeterEditor room={meterEdit} onClose={()=>setMeterEdit(null)} onSave={async room=>{await saveRoom(room);setMeterEdit(null)}}/></>}
 </main>
}

function Nav({icon,label,active,onClick}:{icon:React.ReactNode;label:string;active:boolean;onClick:()=>void}){return <button className={active?"active":""} title={label} onClick={onClick}>{icon}<span>{label}</span></button>}
function Dashboard({rooms,totals,bill,setView}:{rooms:Room[];totals:Totals;bill:(r:Room)=>number;setView:(v:View)=>void}){const occupied=rooms.filter(r=>r.tenant).length,paid=rooms.filter(r=>r.status==="paid").length,pending=rooms.filter(r=>r.status==="pending").length,draft=rooms.length-paid-pending;return <>
 <div className="overview-grid"><Metric label="อาคาร / ทำเล" value="3" suffix="แห่ง" icon={<Building2/>} tint="mint"/><Metric label="ห้องทั้งหมด" value="14" suffix="ห้อง" icon={<Home/>} tint="mint"/><Metric label="ห้องมีผู้เช่า" value={String(occupied)} suffix="ห้อง" icon={<Users/>}/><Metric label="อัตราการเช่า" value={`${Math.round(occupied/rooms.length*100)}%`} icon={<CircleGauge/>}/></div>
 <div className="money-grid"><Metric label="ค่าน้ำ" value={money(totals.water)} suffix="บาท" icon={<Droplets/>} tint="blue"/><Metric label="ค่าไฟฟ้า" value={money(totals.power)} suffix="บาท" icon={<Zap/>} tint="orange"/><Metric label="ค่าเช่า" value={money(totals.rent)} suffix="บาท" icon={<Home/>} tint="green"/><Metric label="บิล / ใบแจ้งหนี้" value={String(rooms.filter(r=>r.status!=="draft").length)} suffix="รายการ" icon={<FileText/>} tint="blue"/><Metric label="ใบเสร็จรับเงิน" value={String(paid)} suffix="รายการ" icon={<ReceiptText/>} tint="green"/></div>
 <div className="dashboard-lower"><article className="panel status-panel"><h2>สถานะการเก็บค่าเช่า</h2><div className="donut" style={{background:`conic-gradient(#147654 0 ${paid/14*100}%,#f39a39 0 ${(paid+pending)/14*100}%,#e7ebe8 0)`}}><span>{paid}<small>ชำระแล้ว</small></span></div><div className="legend"><p><i className="g"/>ชำระแล้ว <b>{paid} ห้อง</b></p><p><i className="o"/>รอชำระ <b>{pending} ห้อง</b></p><p><i/>ค้างชำระ <b>{draft} ห้อง</b></p></div></article>
 <article className="panel recent"><div className="panel-title"><h2>รายการล่าสุด</h2><button onClick={()=>setView("bills")}>ดูทั้งหมด</button></div>{rooms.slice(0,5).map(r=><div className="activity" key={r.id}><span className={r.status==="paid"?"green-icon":r.status==="pending"?"orange-icon":"blue-icon"}>{r.status==="paid"?<ReceiptText/>:r.status==="pending"?<Zap/>:<Droplets/>}</span><div><b>ห้อง {r.id} · {r.tenant||"ว่าง"}</b><small>ค่าเช่าและค่าสาธารณูปโภค กรกฎาคม 2569</small></div><strong>฿{money(bill(r))}</strong><em className={r.status}>{r.status==="paid"?"ชำระแล้ว":r.status==="pending"?"รอชำระ":"รอออกบิล"}</em></div>)}</article></div>
 </>}
function Metric({label,value,suffix,icon,tint=""}:{label:string;value:string;suffix?:string;icon:React.ReactNode;tint?:string}){return <article className={`metric ${tint}`}><div><small>{label}</small><strong>{value} <em>{suffix}</em></strong></div><span>{icon}</span></article>}
function Toolbar({query,setQuery}:{query:string;setQuery:(v:string)=>void}){return <div className="toolbar"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหาห้องหรือชื่อผู้เช่า"/></label></div>}
function RoomsView({rooms,query,setQuery,locations,onEdit}:{rooms:Room[];query:string;setQuery:(v:string)=>void;locations:Location[];onEdit:(r:Room)=>void}){return <section className="panel list-panel"><div className="panel-title"><div><h2>ห้องพักทั้งหมด</h2><p>แก้ไขผู้เช่า ค่าเช่า และข้อมูลห้อง</p></div><Toolbar query={query} setQuery={setQuery}/></div><div className="room-grid">{rooms.map(r=><button className="room-tile" key={r.id} onClick={()=>onEdit(r)}><div><span>{r.id}</span><em className={r.status}/></div><h3>ห้อง {r.id}</h3><p>{r.tenant||"ห้องว่าง"}</p><small>{locations.find(l=>l.id===r.site)?.name} · ฿{money(r.rent)}/เดือน</small><b><Pencil/> แก้ไขข้อมูล</b></button>)}</div></section>}
function MetersView({rooms,onEdit}:{rooms:Room[];onEdit:(r:Room)=>void}){return <section className="panel list-panel"><div className="panel-title"><div><h2>จดมิเตอร์ประจำเดือน</h2><p>กรอกเลขครั้งใหม่ ระบบคำนวณหน่วยให้อัตโนมัติ</p></div></div><table><thead><tr><th>ห้อง</th><th>ผู้เช่า</th><th>น้ำ ครั้งก่อน → ครั้งใหม่</th><th>ไฟ ครั้งก่อน → ครั้งใหม่</th><th></th></tr></thead><tbody>{rooms.map(r=><tr key={r.id}><td><b>{r.id}</b></td><td>{r.tenant||"ว่าง"}</td><td>{r.oldWater} → <b>{r.newWater}</b> <small>({r.newWater-r.oldWater} หน่วย)</small></td><td>{r.oldElectric} → <b>{r.newElectric}</b> <small>({r.newElectric-r.oldElectric} หน่วย)</small></td><td><button className="edit-btn" onClick={()=>onEdit(r)}><Pencil/> กรอกมิเตอร์</button></td></tr>)}</tbody></table></section>}
function BillsView({rooms,bill,onEdit}:{rooms:Room[];bill:(r:Room)=>number;onEdit:(r:Room)=>void}){return <section className="panel list-panel"><div className="panel-title"><div><h2>บิลเดือนกรกฎาคม 2569</h2><p>ตรวจยอด เปลี่ยนสถานะ และพิมพ์บิล</p></div></div><table><thead><tr><th>ห้อง</th><th>ผู้เช่า</th><th>ยอดสุทธิ</th><th>สถานะ</th><th></th></tr></thead><tbody>{rooms.map(r=><tr key={r.id}><td><b>{r.id}</b></td><td>{r.tenant||"ว่าง"}</td><td><strong>฿{money(bill(r))}</strong></td><td><em className={`pill ${r.status}`}>{r.status==="paid"?"ชำระแล้ว":r.status==="pending"?"รอชำระ":"ยังไม่ออกบิล"}</em></td><td><button className="edit-btn" onClick={()=>onEdit(r)}><FileText/> เปิดรายการ</button></td></tr>)}</tbody></table></section>}
function TenantsView({rooms,onEdit}:{rooms:Room[];onEdit:(r:Room)=>void}){return <section className="panel list-panel"><div className="panel-title"><div><h2>รายชื่อผู้เช่า</h2><p>กดที่รายชื่อเพื่อแก้ข้อมูลติดต่อ</p></div></div><div className="tenant-grid">{rooms.filter(r=>r.tenant).map(r=><button key={r.id} onClick={()=>onEdit(r)}><span>{r.tenant.charAt(0)}</span><div><b>{r.tenant}</b><small>ห้อง {r.id} · จุด {r.site}</small><em>{r.phone||"ยังไม่มีเบอร์โทร"}</em></div><Pencil/></button>)}</div></section>}
function SettingsView({locations,onSave}:{locations:Location[];onSave:(l:Location)=>void}){return <section className="settings-grid">{locations.map(l=><LocationForm key={l.id} location={l} onSave={onSave}/>)}</section>}
function LocationForm({location,onSave}:{location:Location;onSave:(l:Location)=>void}){const [form,setForm]=useState(location);return <form className="panel setting-card" onSubmit={e=>{e.preventDefault();onSave(form)}}><div className="setting-icon"><Building2/></div><h2>{location.name}</h2><label>ชื่อจุดเช่า<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>ค่าน้ำต่อหน่วย<input type="number" value={form.waterRate} onChange={e=>setForm({...form,waterRate:Number(e.target.value)})}/></label><label>ค่าไฟต่อหน่วย<input type="number" step="0.01" value={form.electricRate} onChange={e=>setForm({...form,electricRate:Number(e.target.value)})}/></label><button className="save"><Check/> บันทึก</button></form>}
function RoomEditor({room,location,onClose,onSave}:{room:Room;location:Location;onClose:()=>void;onSave:(r:Room)=>void}){const [f,setF]=useState(room);const submit=(e:FormEvent)=>{e.preventDefault();onSave(f)};return <form className="editor" onSubmit={submit}><div className="editor-head"><div><small>{location.name}</small><h2>แก้ไขห้อง {room.id}</h2></div><button type="button" onClick={onClose}><X/></button></div><div className="form-grid"><label className="wide">ชื่อผู้เช่า<input value={f.tenant} onChange={e=>setF({...f,tenant:e.target.value})} placeholder="เว้นว่างหากไม่มีผู้เช่า"/></label><label className="wide">เบอร์โทร<input value={f.phone} onChange={e=>setF({...f,phone:e.target.value})} placeholder="08x-xxx-xxxx"/></label><label className="wide">ค่าเช่าต่อเดือน<input type="number" value={f.rent} onChange={e=>setF({...f,rent:Number(e.target.value)})}/></label><div className="form-section wide"><Droplets/> มิเตอร์น้ำ</div><label>ครั้งก่อน<input type="number" value={f.oldWater} onChange={e=>setF({...f,oldWater:Number(e.target.value)})}/></label><label>ครั้งใหม่<input type="number" value={f.newWater} onChange={e=>setF({...f,newWater:Number(e.target.value)})}/></label><div className="form-section wide"><Zap/> มิเตอร์ไฟ</div><label>ครั้งก่อน<input type="number" value={f.oldElectric} onChange={e=>setF({...f,oldElectric:Number(e.target.value)})}/></label><label>ครั้งใหม่<input type="number" value={f.newElectric} onChange={e=>setF({...f,newElectric:Number(e.target.value)})}/></label><label className="wide">สถานะบิล<select value={f.status} onChange={e=>setF({...f,status:e.target.value as Status})}><option value="draft">ยังไม่ออกบิล</option><option value="pending">รอชำระ</option><option value="paid">ชำระแล้ว</option></select></label></div><div className="editor-actions"><button type="button" onClick={onClose}>ยกเลิก</button><button className="save" type="submit"><Check/> บันทึกข้อมูล</button></div></form>}

function MeterEditor({room,onClose,onSave}:{room:Room;onClose:()=>void;onSave:(r:Room)=>Promise<void>|void}){
 const [water,setWater]=useState(room.newWater||room.oldWater),[power,setPower]=useState(room.newElectric||room.oldElectric),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(room.meterPhotoKey?`/api/meter-photo?key=${encodeURIComponent(room.meterPhotoKey)}`:""),[saving,setSaving]=useState(false),[error,setError]=useState("");
 async function submit(e:FormEvent){e.preventDefault();if(water<room.oldWater||power<room.oldElectric){setError("เลขมิเตอร์ใหม่ต้องไม่น้อยกว่าเดือนก่อน");return}setSaving(true);let key=room.meterPhotoKey||"";try{if(file){const data=new FormData();data.append("file",file);data.append("roomId",room.id);const res=await fetch("/api/meter-photo",{method:"POST",body:data});const json=await res.json();if(!res.ok)throw new Error(json.error||"อัปโหลดรูปไม่สำเร็จ");key=json.key}await onSave({...room,newWater:water,newElectric:power,meterPhotoKey:key});}catch(err){setError(err instanceof Error?err.message:"บันทึกไม่สำเร็จ");setSaving(false)}}
 function choose(f?:File){if(!f)return;setFile(f);setPreview(URL.createObjectURL(f));setError("")}
 return <form className="editor meter-editor" onSubmit={submit}><div className="editor-head"><div><small>รอบบิล กรกฎาคม 2569</small><h2>จดมิเตอร์ห้อง {room.id}</h2></div><button type="button" onClick={onClose}><X/></button></div><div className="meter-note">กรอกเฉพาะเลขที่เห็นบนมิเตอร์เดือนนี้ ระบบจำเลขเดือนก่อนให้แล้ว</div><div className="new-meter-card water"><span><Droplets/></span><div><small>เลขเดือนก่อน</small><b>{room.oldWater}</b></div><label>เลขเดือนใหม่<input inputMode="decimal" type="number" min={room.oldWater} value={water} onChange={e=>setWater(Number(e.target.value))}/><em>ใช้ไป {Math.max(0,water-room.oldWater)} หน่วย</em></label></div><div className="new-meter-card power"><span><Zap/></span><div><small>เลขเดือนก่อน</small><b>{room.oldElectric}</b></div><label>เลขเดือนใหม่<input inputMode="decimal" type="number" min={room.oldElectric} value={power} onChange={e=>setPower(Number(e.target.value))}/><em>ใช้ไป {Math.max(0,power-room.oldElectric)} หน่วย</em></label></div><label className="photo-upload">{preview?<Image src={preview} alt="รูปมิเตอร์" width={640} height={360} unoptimized/>:<span><Camera/><b>แนบรูปมิเตอร์</b><small>ถ่ายรูปใหม่หรือเลือกรูปจากเครื่อง</small></span>}<input type="file" accept="image/*" capture="environment" onChange={e=>choose(e.target.files?.[0])}/><em><Upload/> {preview?"เปลี่ยนรูป":"เลือกรูป"}</em></label>{error&&<p className="form-error">{error}</p>}<div className="editor-actions"><button type="button" onClick={onClose}>ยกเลิก</button><button className="save" disabled={saving} type="submit"><Check/> {saving?"กำลังบันทึก...":"บันทึกมิเตอร์"}</button></div></form>}
